services:
  gate:
    build: .
    ports:
      - "8080:8080"
    environment:
      PASSWORD: "changeme"
      UPSTREAM: "http://app:80"
      SECRET: "replace-with-openssl-rand-hex-32"
    depends_on:
      - app

  app:
    image: traefik/whoami
